version: "3"
services:
  pg:
    build:
      context: ./
      dockerfile: ./Dockersetup/postgres.dockerfile
    image: p5pg
    # Set up some environment variables. Password is stored in the .env file
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: "$POSTGRES_PASSWORD"
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - ./data:/data

  af:
      build:
        context: ./
        dockerfile: ./Dockersetup/airflow.dockerfile
      image: p5af
      environment:
        AIRFLOW_CONN_PG: "$AIRFLOW_CONN_PG"
      ports:
        - "8080:8080"
      volumes:
        - ./airflowcode/dags:/usr/local/airflow/dags
        - ./airflowcode/plugins:/usr/local/airflow/plugins
