version: "3.8"
services:
  airflow:
      build:
        context: ./
        dockerfile: ./Dockersetup/airflow.dockerfile
      image: ogierpaul/p5af
      environment:
        AIRFLOW_CONN_AA_RS: "$AIRFLOW_CONN_AA_RS"
        AWS_ARN: "$AWS_ARN"
      ports:
        - "8080:8080"
      volumes:
        - ./airflowcode/dags:/usr/local/airflow/dags
        - ./airflowcode/plugins:/usr/local/airflow/plugins
